"""Page copy for batch 3: smart plugs, door/window sensors, motion sensors, smart locks.
Imported at the bottom of meta.py."""


def _p(family, family_title, noun, title, subtitle, intro, ceiling, guide):
    return {"family": family, "family_title": family_title, "noun": noun, "title": title,
            "subtitle": subtitle, "intro": intro, "reviews_ceiling": ceiling, "guide": guide}


SAFETY_PLUG = {"q": "Are smart plugs safe for heaters and air conditioners?",
               "a": "Only if the plug's rating covers the appliance's draw and the maker allows it. Many plugs are rated 15 A, but heaters run near that limit for hours. Check the appliance's manual; some say not to use any timer or smart plug."}
PLUG_GUIDE = [
    {"q": "What can I plug into a smart plug?",
     "a": "Lamps, fans, coffee makers, holiday lights, and anything else that turns on with a physical switch left in the on position. Check the plug's amp rating (most are 15 A) before plugging in anything that draws a lot of power."},
    {"q": "Is energy monitoring worth paying for?",
     "a": "If you want to know what a fridge, dehumidifier, or entertainment center costs to run, yes. Energy-monitoring plugs also let you trigger automations, like an alert when the washer finishes."},
    {"q": "Will a smart plug block the second outlet?",
     "a": "Bulky plugs often cover the other socket. Mini designs leave it free, so check the shape before you buy several."},
    SAFETY_PLUG,
]
SENSOR_BATT = {"q": "How long do the batteries last?",
               "a": "Most battery sensors on these lists are rated for one to three years, depending on how often they report. Low-power radios like Zigbee, Z-Wave, and Thread last much longer than Wi-Fi."}
DOOR_GUIDE = [
    {"q": "How do door and window sensors work?",
     "a": "A magnet goes on the door or window and the sensor goes on the frame. When the two separate, the sensor reports open. Mount them within the gap the listing specifies, usually under an inch."},
    SENSOR_BATT,
    {"q": "Can I use these as a security system?",
     "a": "They can trigger alerts and sirens through your smart home system, but they aren't a monitored alarm. For insurance discounts or police dispatch you need a professionally monitored system."},
]
MOTION_GUIDE = [
    {"q": "PIR motion or mmWave presence?",
     "a": "PIR sensors detect movement and are cheap with long battery life, but they think a room is empty when you sit still. mmWave presence sensors detect a person sitting still, so lights stay on while you read, but many need wired power."},
    SENSOR_BATT,
    {"q": "Where should I put a motion sensor?",
     "a": "In a corner about 6 to 8 feet up, facing across the room rather than straight at the doorway. Keep PIR sensors away from heat vents and direct sun, which cause false triggers."},
]
LOCK_GUIDE = [
    {"q": "Will a smart lock fit my door?",
     "a": "Most smart deadbolts fit a standard US door with a 2-1/8 in. bore hole and a 2-3/8 or 2-3/4 in. backset. Retrofit locks like Level Bolt replace only the inside parts and keep your existing key and hardware."},
    {"q": "What happens if the batteries die?",
     "a": "Locks warn you in their app before the batteries run out. Most also have a backup key, an emergency power point, or both. Check the listing for which one yours has."},
    {"q": "Is a smart lock secure?",
     "a": "Look for encrypted radios (Z-Wave S2, Matter, Thread, or the maker's encrypted Bluetooth), auto-lock, and an activity log. ANSI/BHMA grade ratings describe physical strength; Grade 2 or better is typical for a front door."},
]

PAGES = {
    "z-wave-smart-plugs": _p("smart-plugs", "Smart plugs", "plug", "The 10 Best Z-Wave Smart Plugs",
        "Plug-in Z-Wave outlets that also strengthen your mesh, ranked from live Amazon data.",
        "We pulled the Z-Wave smart plugs selling on Amazon and scored them on rating, review volume, and features: 800 Series Long Range radios, energy monitoring, and outdoor ratings. Every Z-Wave plug also acts as a repeater for the rest of your network.",
        900, PLUG_GUIDE),
    "zigbee-smart-plugs": _p("smart-plugs", "Smart plugs", "plug", "The 10 Best Zigbee Smart Plugs",
        "Cheap Zigbee outlets that double as mesh repeaters, ranked from live Amazon data.",
        "We pulled the Zigbee smart plugs selling on Amazon and scored them on rating, review volume, and features: energy monitoring, open Zigbee 3.0 pairing, and signal repeating. Plugs are the easiest way to strengthen a Zigbee mesh.",
        6000, PLUG_GUIDE),
    "wifi-smart-plugs": _p("smart-plugs", "Smart plugs", "plug", "The 10 Best Wi-Fi Smart Plugs",
        "No-hub smart plugs that connect straight to your router.",
        "We pulled the best-selling Wi-Fi smart plugs on Amazon and scored them on rating, review volume, and features: energy monitoring, outdoor ratings, and Apple Home support. Wi-Fi plugs with Matter are on our Matter page.",
        100000, PLUG_GUIDE),
    "matter-smart-plugs": _p("smart-plugs", "Smart plugs", "plug", "The 10 Best Matter Smart Plugs",
        "Plugs that work with Apple Home, Google Home, Alexa, SmartThings, and Home Assistant at once.",
        "We pulled the Matter smart plugs selling on Amazon and scored them on rating, review volume, and features: energy monitoring and outdoor ratings. These run Matter over Wi-Fi; Thread plugs have their own page.",
        3000, PLUG_GUIDE),
    "thread-smart-plugs": _p("smart-plugs", "Smart plugs", "plug", "The Best Thread Smart Plugs",
        "Matter-over-Thread plugs that strengthen your Thread network, ranked.",
        "Thread plugs are the easiest way to extend a Thread network, because each one routes signal for other devices. We pulled the ones selling on Amazon and scored them on rating, review volume, and features. Every plug here needs a Thread border router.",
        500, PLUG_GUIDE),
    "z-wave-door-sensors": _p("door-sensors", "Door and window sensors", "sensor", "The Best Z-Wave Door and Window Sensors",
        "Battery Z-Wave contact sensors, ranked from live Amazon data.",
        "We pulled the Z-Wave door and window sensors selling on Amazon and scored them on rating, review volume, and features: 800 Series Long Range radios, extra sensors, and recessed designs. The list is short because few makers still sell standalone Z-Wave contact sensors.",
        400, DOOR_GUIDE),
    "zigbee-door-sensors": _p("door-sensors", "Door and window sensors", "sensor", "The 10 Best Zigbee Door and Window Sensors",
        "Tiny, cheap Zigbee contact sensors, ranked from live Amazon data.",
        "We pulled the Zigbee door and window sensors selling on Amazon and scored them on rating, review volume, and features: open Zigbee 3.0 pairing and size. Zigbee is the cheapest way to cover every door and window.",
        6000, DOOR_GUIDE),
    "wifi-door-sensors": _p("door-sensors", "Door and window sensors", "sensor", "The Best Wi-Fi Door and Window Sensors",
        "No-hub contact sensors that connect straight to your router.",
        "We pulled the Wi-Fi door and window sensors selling on Amazon and scored them on rating, review volume, and features. Wi-Fi sensors need no hub, but they use more battery, and almost all of them run on the cloud-based Smart Life (Tuya) app.",
        500, DOOR_GUIDE),
    "matter-door-sensors": _p("door-sensors", "Door and window sensors", "sensor", "The Best Matter Door and Window Sensors",
        "Matter-over-Thread contact sensors for every major platform.",
        "Matter door and window sensors run over Thread, so every one here needs a Thread border router. There are only a few on Amazon so far. We scored them on rating, review volume, and features.",
        1500, DOOR_GUIDE),
    "z-wave-motion-sensors": _p("motion-sensors", "Motion sensors", "sensor", "The Best Z-Wave Motion Sensors",
        "Battery and wired Z-Wave motion sensors, ranked from live Amazon data.",
        "We pulled the Z-Wave motion sensors selling on Amazon and scored them on rating, review volume, and features: 800 Series Long Range radios, extra sensors like temperature and light, and pet immunity.",
        800, MOTION_GUIDE),
    "zigbee-motion-sensors": _p("motion-sensors", "Motion sensors", "sensor", "The 10 Best Zigbee Motion and Presence Sensors",
        "PIR motion and mmWave presence sensors on Zigbee, ranked.",
        "We pulled the Zigbee motion and presence sensors selling on Amazon and scored them on rating, review volume, and features: presence detection, light sensing, and open Zigbee 3.0 pairing.",
        1500, MOTION_GUIDE),
    "wifi-motion-sensors": _p("motion-sensors", "Motion sensors", "sensor", "The Best Wi-Fi Motion Sensors",
        "No-hub motion and presence sensors that connect to your router.",
        "We pulled the Wi-Fi motion and presence sensors selling on Amazon and scored them on rating, review volume, and features. Battery Wi-Fi motion sensors tend to react slower than Zigbee or Z-Wave ones, because they sleep between events to save power.",
        1000, MOTION_GUIDE),
    "matter-motion-sensors": _p("motion-sensors", "Motion sensors", "sensor", "The Best Matter Motion and Presence Sensors",
        "Motion and presence sensors that work with every major platform.",
        "We pulled the Matter motion and presence sensors selling on Amazon and scored them on rating, review volume, and features. Most run Matter over Thread and need a Thread border router; the table shows which.",
        700, MOTION_GUIDE),
    "z-wave-door-locks": _p("locks", "Smart locks", "lock", "The Best Z-Wave Smart Locks",
        "Z-Wave deadbolts for hub-based smart homes, ranked from live Amazon data.",
        "We pulled the Z-Wave smart locks selling on Amazon and scored them on rating, review volume, and features: 800 Series Long Range radios, fingerprint readers, and touchscreens. Z-Wave locks need a Z-Wave hub.",
        6000, LOCK_GUIDE),
    "wifi-locks": _p("locks", "Smart locks", "lock", "The 10 Best Wi-Fi Smart Locks",
        "Smart deadbolts with built-in Wi-Fi, no hub needed.",
        "We pulled the best-selling Wi-Fi smart locks on Amazon and scored them on rating, review volume, and features: fingerprint readers, auto-lock, and Apple Home Key. Locks with Matter are on our Matter page.",
        17000, LOCK_GUIDE),
    "bluetooth-locks": _p("locks", "Smart locks", "lock", "The 10 Best Bluetooth Smart Locks",
        "App-controlled locks that talk to your phone directly.",
        "We pulled the Bluetooth smart locks selling on Amazon and scored them on rating, review volume, and features: fingerprint readers, keypads, and handles. Bluetooth locks work when you're nearby; remote access needs a separate Wi-Fi gateway.",
        5000, LOCK_GUIDE),
    "matter-locks": _p("locks", "Smart locks", "lock", "The 10 Best Matter Smart Locks",
        "Smart locks that work with Apple Home, Google Home, Alexa, SmartThings, and Home Assistant.",
        "We pulled the Matter smart locks selling on Amazon and scored them on rating, review volume, and features: Apple Home Key, fingerprint readers, and auto-lock. Most run Matter over Thread and need a Thread border router.",
        11000, LOCK_GUIDE),
    "zigbee-locks": _p("locks", "Smart locks", "lock", "The Best Zigbee Smart Locks",
        "Zigbee deadbolts and conversion kits, ranked from live Amazon data.",
        "Zigbee locks are mostly Kwikset's Zigbee 3.0 models and Aqara's hub-based locks. We pulled what's selling on Amazon and scored it on rating, review volume, and features.",
        3000, LOCK_GUIDE),
}
