"""Page copy for batch 4: leak sensors, bulbs, thermostats, cameras and doorbells.
Imported at the bottom of meta.py."""
from meta_batch3 import _p, SENSOR_BATT

LEAK_GUIDE = [
    {"q": "Where should leak sensors go?",
     "a": "Anywhere water can appear without you seeing it: under sinks, behind the toilet, next to the water heater, under the dishwasher and washing machine, and near the sump pump. Put them flat on the floor where water would pool first."},
    {"q": "Do I want a built-in alarm?",
     "a": "Yes, if the sensor might be your only warning. A loud local siren works even if your internet or hub is down. App and hub alerts are better when you're away."},
    SENSOR_BATT,
    {"q": "Can a leak sensor shut off the water?",
     "a": "Not on its own. Paired with a smart water shut-off valve through your hub or app, it can close the main valve automatically when it detects a leak."},
]
BULB_GUIDE = [
    {"q": "Smart bulbs or smart switches?",
     "a": "Bulbs give you color and tunable white, and they work in lamps. Switches are better for fixtures with several bulbs and keep the wall switch working for guests. Don't put smart bulbs on an ordinary dimmer, and keep the wall switch on, or the bulbs lose power and go offline."},
    {"q": "What do lumens and color temperature mean?",
     "a": "Lumens measure brightness: about 800 lm matches an old 60 W bulb and 1,100 lm a 75 W bulb. Color temperature in kelvin runs from warm (2,700 K, cozy) to cool (5,000 K and up, daylight)."},
    {"q": "Do bulbs need a hub?",
     "a": "Wi-Fi and Matter-over-Wi-Fi bulbs connect to your router directly. Zigbee bulbs need a Zigbee hub, such as a Hue Bridge or an Echo with Zigbee built in. Matter-over-Thread bulbs need a Thread border router."},
]
THERMO_GUIDE = [
    {"q": "Do I need a C-wire?",
     "a": "Most smart thermostats need constant power from a C (common) wire. Some include a power adapter for homes without one, and a few run on batteries. Check your current thermostat's wiring before you buy."},
    {"q": "Will it work with my heating and cooling system?",
     "a": "Most smart thermostats handle standard 24 V forced-air and heat pump systems. Line-voltage electric baseboard heaters need a different, line-voltage thermostat. Check the maker's compatibility checker before buying."},
    {"q": "Do remote sensors matter?",
     "a": "If some rooms run hotter or colder than where the thermostat hangs, yes. Remote room sensors let the thermostat average temperatures or focus on the rooms you're using."},
]
CAM_GUIDE = [
    {"q": "Do I need a subscription?",
     "a": "Many cameras store clips in the cloud only with a monthly plan. Others record to a microSD card or a base station for free. Check what the free tier includes before you buy several."},
    {"q": "Battery or wired?",
     "a": "Battery cameras go anywhere but sleep between events, so they can miss the first second of motion and need recharging. Wired cameras record continuously and react faster but need an outlet nearby."},
    {"q": "2.4 GHz or 5 GHz Wi-Fi?",
     "a": "Most cameras use 2.4 GHz, which reaches farther through walls. Some newer ones support 5 GHz for faster streaming close to the router."},
]
DOORBELL_GUIDE = [
    {"q": "Wired or battery doorbell?",
     "a": "Wired doorbells use your existing doorbell wiring for constant power and faster response, and they ring your existing chime. Battery doorbells install anywhere but need recharging every few months."},
] + CAM_GUIDE[:1]

PAGES = {
    "z-wave-leak-sensors": _p("leak-sensors", "Leak sensors", "sensor", "The Best Z-Wave Water Leak Sensors",
        "Z-Wave flood sensors for your hub, ranked from live Amazon data.",
        "We pulled the Z-Wave water leak sensors selling on Amazon and scored them on rating, review volume, and features: 800 Series Long Range radios, probes and cables, and freeze or temperature alerts.",
        500, LEAK_GUIDE),
    "zigbee-leak-sensors": _p("leak-sensors", "Leak sensors", "sensor", "The Best Zigbee Water Leak Sensors",
        "Cheap Zigbee leak sensors, many with built-in alarms, ranked.",
        "We pulled the Zigbee water leak sensors selling on Amazon and scored them on rating, review volume, and features: built-in sirens, sensing cables, and open Zigbee 3.0 pairing.",
        4000, LEAK_GUIDE),
    "wifi-leak-sensors": _p("leak-sensors", "Leak sensors", "sensor", "The 10 Best Wi-Fi Water Leak Sensors",
        "Leak sensors and kits that alert your phone without a smart home hub.",
        "We pulled the Wi-Fi water leak sensors selling on Amazon and scored them on rating, review volume, and features. Some connect straight to Wi-Fi; several popular kits use their own long-range radio to a base station that connects to Wi-Fi. The table shows which.",
        7000, LEAK_GUIDE),
    "matter-leak-sensors": _p("leak-sensors", "Leak sensors", "sensor", "The Best Matter Water Leak Sensors",
        "Leak sensors that work with every major smart home platform.",
        "Matter leak sensors are new, so this list is short. We scored the ones on Amazon on rating, review volume, and features.",
        400, LEAK_GUIDE),
    "zigbee-bulbs": _p("bulbs", "Smart bulbs", "bulb", "The Best Zigbee Smart Bulbs",
        "Zigbee bulbs for Hue bridges, Echo hubs, and open Zigbee hubs, ranked.",
        "We pulled the Zigbee smart bulbs selling on Amazon and scored them on rating, review volume, and features: full color, brightness, and open Zigbee pairing. Zigbee bulbs also strengthen your Zigbee mesh.",
        8000, BULB_GUIDE),
    "wifi-bulbs": _p("bulbs", "Smart bulbs", "bulb", "The 10 Best Wi-Fi Smart Bulbs",
        "No-hub smart bulbs that connect straight to your router.",
        "We pulled the best-selling Wi-Fi smart bulbs on Amazon and scored them on rating, review volume, and features: full color, brightness, and voice assistant support. Wi-Fi bulbs with Matter are on our Matter page.",
        28000, BULB_GUIDE),
    "matter-bulbs": _p("bulbs", "Smart bulbs", "bulb", "The 10 Best Matter Smart Bulbs",
        "Bulbs that work with Apple Home, Google Home, Alexa, SmartThings, and Home Assistant.",
        "We pulled the Matter smart bulbs selling on Amazon and scored them on rating, review volume, and features: full color, brightness, and Thread versus Wi-Fi. The table shows which radio each bulb uses.",
        2500, BULB_GUIDE),
    "z-wave-thermostats": _p("thermostats", "Thermostats", "thermostat", "The Best Z-Wave Thermostats",
        "Every Z-Wave thermostat we found on Amazon, ranked.",
        "Z-Wave thermostats are rare now; most makers moved to Wi-Fi. We scored the ones on Amazon on rating, review volume, and features. Two are built mainly for security panels.",
        800, THERMO_GUIDE),
    "wifi-thermostats": _p("thermostats", "Thermostats", "thermostat", "The 10 Best Wi-Fi Smart Thermostats",
        "Smart thermostats that connect to your router, ranked from live Amazon data.",
        "We pulled the best-selling Wi-Fi smart thermostats on Amazon and scored them on rating, review volume, and features: remote sensors, Apple Home support, and C-wire flexibility. Thermostats with Matter are on our Matter page.",
        30000, THERMO_GUIDE),
    "matter-thermostats": _p("thermostats", "Thermostats", "thermostat", "The Best Matter Smart Thermostats",
        "Thermostats that work with every major smart home platform.",
        "We pulled the Matter smart thermostats selling on Amazon and scored them on rating, review volume, and features. Matter thermostats can be controlled from Apple Home, Google Home, Alexa, SmartThings, and Home Assistant at once.",
        30000, THERMO_GUIDE),
    "wifi-indoor-cameras": _p("indoor-cameras", "Indoor cameras", "camera", "The 10 Best Indoor Wi-Fi Security Cameras",
        "Indoor cameras for home security, pets, and babies, ranked from live Amazon data.",
        "We pulled the best-selling indoor Wi-Fi cameras on Amazon and scored them on rating, review volume, and features: pan and tilt, local storage, and resolution.",
        45000, CAM_GUIDE),
    "wifi-outdoor-cameras": _p("outdoor-cameras", "Outdoor cameras", "camera", "The 10 Best Outdoor Wi-Fi Security Cameras",
        "Weatherproof Wi-Fi cameras, battery and wired, ranked from live Amazon data.",
        "We pulled the best-selling outdoor Wi-Fi cameras on Amazon and scored them on rating, review volume, and features: local storage, solar or battery power, and resolution.",
        65000, CAM_GUIDE),
    "wifi-doorbells": _p("doorbells", "Video doorbells", "doorbell", "The 10 Best Video Doorbells",
        "Wi-Fi video doorbells, wired and battery, ranked from live Amazon data.",
        "We pulled the best-selling video doorbells on Amazon and scored them on rating, review volume, and features: local storage, wired or battery power, and resolution.",
        56000, DOORBELL_GUIDE),
}
