"""Page copy for batch 9: light strips, smart displays, relays, fan controls, presence sensors,
more blinds, in-wall outlets, IR remotes, air purifiers, AC controllers, energy monitors,
security systems, mesh routers, EV chargers, pet feeders, pet cameras, baby monitors, robot mowers.
Imported at the bottom of meta.py."""
from meta_batch3 import _p, SENSOR_BATT

STRIP_GUIDE = [
    {"q": "RGB, RGBIC, or RGBWW: what's the difference?",
     "a": "RGB strips show one color at a time along the whole strip. RGBIC strips can show several colors at once, for rainbow and chase effects. RGBWW strips add real white LEDs, which look much better for everyday lighting than white mixed from red, green, and blue."},
    {"q": "Can I cut a light strip?",
     "a": "Most strips can be cut at the marked lines, but the cut-off piece usually can't be reconnected without connectors. Measure first and buy close to the length you need."},
    {"q": "Do light strips need a hub?",
     "a": "Wi-Fi strips connect to your router. Hue and other Zigbee strips need a Zigbee hub or bridge. Matter strips work with Apple Home, Google Home, Alexa, SmartThings, and Home Assistant."},
]
DISPLAY_GUIDE = [
    {"q": "Smart display or smart speaker?",
     "a": "A display adds a screen for cameras, recipes, calendars, and smart home controls. If you want to see your doorbell camera or control lights by touch, get a display. For music and voice only, a speaker is cheaper."},
    {"q": "Can a smart display be my hub?",
     "a": "Some can. Several Echo Show models have a built-in Zigbee hub or Thread border router, and Google's Nest Hub (2nd gen) is a Thread border router and Matter controller. Check the listing if you want it to run your devices."},
    {"q": "What about privacy?",
     "a": "Most displays have a camera shutter and a microphone off switch. Put one with a camera in a kitchen or office rather than a bedroom if that bothers you."},
]
RELAY_GUIDE = [
    {"q": "What does a smart relay do?",
     "a": "It hides behind a wall switch, inside a fan canopy, or in an appliance and switches the power, so you keep your existing switch and add smart control. Dry-contact relays can also trigger garage doors, gas fireplaces, and boilers."},
    {"q": "Do I need a neutral wire?",
     "a": "Most relays do. Check your switch box for a bundle of white wires before buying. A few models work without a neutral, and the table notes which."},
    {"q": "Is it safe to install myself?",
     "a": "Only if you're comfortable with household wiring and turn the breaker off first. If you're not sure, have an electrician install it. Never exceed the relay's amp rating."},
]
FAN_GUIDE = [
    {"q": "Will a smart fan control work with my ceiling fan?",
     "a": "Wall fan controls work with fans that are switched from the wall and have a pull chain left on high. If your fan uses a handheld remote and a receiver in the canopy, you need a receiver-based controller instead."},
    {"q": "Can it also control the fan's light?",
     "a": "Some combo switches control both the fan and the light separately, which needs separate wires for the fan and light. Single-function controls only do the fan."},
    {"q": "Why not use a regular dimmer on a fan?",
     "a": "Dimmers aren't designed for fan motors and can make them hum or overheat. Use a control rated for fans."},
]
PRESENCE_GUIDE = [
    {"q": "Presence sensor or motion sensor?",
     "a": "A motion sensor (PIR) sees movement, so lights turn off if you sit still. An mmWave presence sensor detects breathing-level motion, so it knows you're still in the room while you read or work."},
    {"q": "Do presence sensors need power?",
     "a": "Most mmWave sensors need USB or wall power because the radar runs constantly. A few newer battery models combine PIR and mmWave to save power."},
    {"q": "Can it tell where I am in the room?",
     "a": "Some models, like the Aqara FP2, support zones, so a desk, couch, and bed can trigger different automations."},
]
BLIND_GUIDE = [
    {"q": "Retrofit robot or new motorized shade?",
     "a": "Curtain robots and blind tilters attach to what you already have and install in minutes. Motorized shades replace your blinds and look cleaner, but you have to measure and order to size."},
    {"q": "How are they powered?",
     "a": "Most use a rechargeable battery charged over USB-C or a small solar panel. Expect weeks to months per charge depending on use."},
    {"q": "Do I need a hub?",
     "a": "Bluetooth robots need a hub for remote control and automations. Zigbee motors need a Zigbee hub. Wi-Fi models connect directly."},
]
OUTLET_GUIDE = [
    {"q": "In-wall outlet or plug-in smart plug?",
     "a": "An in-wall outlet replaces your receptacle, so nothing sticks out and both sockets stay usable. It needs wiring work. A plug-in smart plug needs no tools."},
    {"q": "Do I need a neutral wire?",
     "a": "Yes, nearly all smart outlets need line, neutral, and ground. Most outlet boxes have them."},
    SENSOR_BATT,
]
IR_GUIDE = [
    {"q": "What can an IR blaster control?",
     "a": "Anything that uses an infrared remote: TVs, air conditioners, fans, fireplaces, soundbars, and older electronics. It needs a clear line of sight to the device."},
    {"q": "Will it know if my TV is on?",
     "a": "Usually not. IR is one-way, so the blaster sends a command but can't confirm the device received it. Some models add a sensor cable or power monitoring to guess the state."},
    {"q": "IR or RF?",
     "a": "IR covers most TVs and AC units. Some ceiling fans, shades, and outlets use radio (RF) remotes, which need a model with RF support."},
]
PURIFIER_GUIDE = [
    {"q": "What size purifier do I need?",
     "a": "Match the room size to the purifier's rated coverage, ideally with some headroom. CADR (clean air delivery rate) is the better number to compare when listings give it."},
    {"q": "What does smart add?",
     "a": "App and voice control, schedules, filter reminders, and an air quality sensor that turns the fan up when the air gets worse. Matter models work with every major platform."},
    {"q": "How much do filters cost?",
     "a": "Replacement filters usually run $15 to $60 and last 6 to 12 months. Check the filter price before you buy the purifier."},
]
AC_GUIDE = [
    {"q": "How does a smart AC controller work?",
     "a": "It sits near your mini-split, window, or portable AC and sends the same infrared signals as its remote, adding app control, schedules, and temperature-based automation."},
    {"q": "Will it work with my AC?",
     "a": "If your AC came with an infrared remote that shows the temperature, almost certainly. Check the maker's compatibility list for your brand."},
    {"q": "Can it replace a thermostat?",
     "a": "For mini-splits, yes: the controller reads the room temperature and adjusts the AC, which is often more accurate than the sensor inside the unit."},
]
ENERGY_GUIDE = [
    {"q": "Do I need an electrician?",
     "a": "Whole-home monitors clip current sensors around wires inside your electrical panel. Many people install them, but it means working inside a live panel. Hire an electrician if you're not comfortable."},
    {"q": "Whole-home or circuit-level?",
     "a": "Two main sensors show your total use. Adding circuit sensors shows which appliances use what, like the dryer, AC, or EV charger."},
    {"q": "Does it work with solar?",
     "a": "Many monitors can track solar production and net metering with extra sensors. Check the listing if you have panels."},
]
SECURITY_GUIDE = [
    {"q": "Do I need professional monitoring?",
     "a": "No. Most kits send phone alerts and sound a siren for free. Paid monitoring adds a call center that dispatches police or fire, and some insurers offer a discount for it."},
    {"q": "What's in a typical kit?",
     "a": "A base station with a siren, a keypad, door and window sensors, and a motion sensor. Larger kits add more sensors and range extenders."},
    {"q": "Will it work if the internet goes down?",
     "a": "The base station's siren still works. Some systems include a cellular backup that keeps alerts going, usually on a paid plan."},
]
MESH_GUIDE = [
    {"q": "Do I need mesh Wi-Fi?",
     "a": "If your router can't reach every room, or you have dozens of smart devices, mesh helps. Several satellites spread the signal and handle more connections than a single router."},
    {"q": "Wi-Fi 6, 6E, or 7?",
     "a": "Wi-Fi 6 is plenty for most homes and smart devices. 6E and 7 add faster bands for newer phones and laptops. Smart home gadgets mostly use 2.4 GHz, which every mesh system supports."},
    {"q": "Can a router be a smart home hub?",
     "a": "Some can. eero 6 and later models include a Thread border router and a Zigbee hub for Alexa."},
]
EV_GUIDE = [
    {"q": "Plug-in or hardwired?",
     "a": "Plug-in chargers use a NEMA 14-50 outlet and can be moved. Hardwired chargers can deliver more current (48 A or more) and are required for some installs. Both need a 240 V circuit."},
    {"q": "How many amps do I need?",
     "a": "A 40 A charger adds about 30 miles of range per hour on most EVs, which covers overnight charging for nearly everyone. Your car's onboard charger may cap the speed anyway."},
    {"q": "What does smart add?",
     "a": "Scheduling for cheap off-peak electricity, charging history, and sometimes utility rebates. Check your utility for EV charger rebates before buying."},
]
PET_FEEDER_GUIDE = [
    {"q": "Dry food only?",
     "a": "Almost all automatic feeders handle dry kibble only. Check the kibble size limits in the listing."},
    {"q": "What if the power or Wi-Fi goes out?",
     "a": "Look for battery backup. Most feeders keep their schedule locally and keep feeding without Wi-Fi; you just lose app control and alerts."},
    {"q": "Do I need the camera version?",
     "a": "A camera lets you watch your pet eat and confirms the food actually dropped. If you just want reliable meals, the non-camera version is cheaper."},
]
PET_CAM_GUIDE = [
    {"q": "Do I need a subscription?",
     "a": "Many pet cameras lock barking alerts, cloud video, and AI features behind a monthly plan. Check what the free tier includes; some Furbo listings require a plan just to activate."},
    {"q": "Treat tossing or just a camera?",
     "a": "Treat cameras let you reward your pet remotely. A regular pan-and-tilt indoor camera is much cheaper if you only want to watch and talk."},
    {"q": "Will it work on my Wi-Fi?",
     "a": "Most need 2.4 GHz Wi-Fi; some also support 5 GHz. Put the camera within good range of your router."},
]
BABY_GUIDE = [
    {"q": "Wi-Fi monitor or local display?",
     "a": "Wi-Fi monitors let you watch from your phone anywhere. Monitors with a parent display work without Wi-Fi in the house. Some do both."},
    {"q": "Do I need a subscription?",
     "a": "Some smart monitors put sleep tracking and cloud video behind a plan. Live view is usually free. Check before you buy."},
    {"q": "Is a security camera good enough?",
     "a": "For basic watching, yes: a cheap pan-and-tilt indoor camera works as a baby monitor. Dedicated monitors add a parent display, lullabies, room temperature, and cry alerts."},
]
MOWER_GUIDE = [
    {"q": "Boundary wire or wire-free?",
     "a": "Older robots need a wire buried around the lawn edge. Newer wire-free models use RTK GPS, LiDAR, or cameras to map the lawn, which saves hours of setup."},
    {"q": "How big a lawn can it handle?",
     "a": "Check the rated area and the slope it can climb. Buy for your lawn size with some headroom."},
    {"q": "Is it safe around kids and pets?",
     "a": "Robot mowers have lift and obstacle sensors and stop the blades, but keep kids and pets off the lawn while it runs, and schedule it for times the yard is empty."},
]

PAGES = {
    "wifi-light-strips": _p("light-strips", "Light strips", "strip", "The 10 Best Smart LED Light Strips",
        "Wi-Fi LED strips for bedrooms, TVs, and gaming setups, ranked from live Amazon data.",
        "We pulled the best-selling Wi-Fi LED light strips on Amazon and scored them on rating, review volume, and features: multicolor RGBIC effects, voice assistant support, and length.",
        40000, STRIP_GUIDE),
    "zigbee-light-strips": _p("light-strips", "Light strips", "strip", "The Best Zigbee Light Strips and Controllers",
        "Philips Hue lightstrips and Zigbee LED strip controllers, ranked.",
        "We pulled the Zigbee light strips and LED strip controllers on Amazon, mostly Philips Hue plus controllers that turn any strip into a Zigbee light, and scored them on rating, review volume, and features.",
        2500, STRIP_GUIDE),
    "matter-light-strips": _p("light-strips", "Light strips", "strip", "The Best Matter Light Strips",
        "LED strips that work with Apple Home, Google Home, Alexa, SmartThings, and Home Assistant.",
        "We pulled the LED light strips on Amazon whose listings name Matter support and scored them on rating, review volume, and features.",
        2000, STRIP_GUIDE),
    "wifi-smart-displays": _p("smart-displays", "Smart displays", "display", "The Best Smart Displays",
        "Echo Show and Nest Hub screens for your kitchen, nightstand, and smart home, ranked.",
        "We pulled the smart displays selling on Amazon and scored them on rating, review volume, and features: screen size, a built-in smart home hub, and a camera for video calls.",
        50000, DISPLAY_GUIDE),
    "z-wave-relays": _p("relays", "Relays and modules", "relay", "The Best Z-Wave Relays and In-Wall Modules",
        "Hidden Z-Wave relays for lights, fans, garage doors, and fireplaces, ranked.",
        "We pulled the Z-Wave relays and in-wall modules on Amazon and scored them on rating, review volume, and features: 800 Series Long Range, dry contacts, and power metering.",
        600, RELAY_GUIDE),
    "zigbee-relays": _p("relays", "Relays and modules", "relay", "The Best Zigbee Relays and In-Wall Modules",
        "Zigbee relays that make any switch or appliance smart, ranked.",
        "We pulled the Zigbee relays and in-wall modules on Amazon and scored them on rating, review volume, and features: open Zigbee 3.0 pairing, dry contacts, and no-neutral options.",
        1500, RELAY_GUIDE),
    "wifi-relays": _p("relays", "Relays and modules", "relay", "The Best Wi-Fi Relays and In-Wall Modules",
        "Shelly and other Wi-Fi relays for hidden smart switching, ranked.",
        "We pulled the Wi-Fi relays and in-wall modules on Amazon and scored them on rating, review volume, and features: power metering, local control, and dry contacts.",
        1500, RELAY_GUIDE),
    "matter-relays": _p("relays", "Relays and modules", "relay", "The Best Matter Relays and In-Wall Modules",
        "Matter relays that work with every major smart home platform, ranked.",
        "We pulled the relays and in-wall modules on Amazon whose listings name Matter and scored them on rating, review volume, and features.",
        1000, RELAY_GUIDE),
    "z-wave-fan-controls": _p("fan-controls", "Fan controls", "control", "The Best Z-Wave Ceiling Fan Controls",
        "Z-Wave fan speed switches and fan-and-light combos, ranked.",
        "Z-Wave fan controls are a small category. We scored the ones on Amazon on rating, review volume, and features: speeds, fan-and-light combos, and Long Range.",
        500, FAN_GUIDE),
    "wifi-fan-controls": _p("fan-controls", "Fan controls", "control", "The 10 Best Smart Ceiling Fan Controls",
        "Wi-Fi fan speed switches, combos, and canopy controllers, ranked from live Amazon data.",
        "We pulled the Wi-Fi ceiling fan controls on Amazon and scored them on rating, review volume, and features: separate fan and light control, speeds, and voice assistants.",
        5000, FAN_GUIDE),
    "lutron-fan-controls": _p("fan-controls", "Fan controls", "control", "The Best Lutron Caseta Fan Controls",
        "Every Caseta fan speed control and fan Pico we found on Amazon, ranked.",
        "Lutron sells one Caseta fan control in a few colors, plus a matching Pico remote. We scored the listings on Amazon on rating and review volume.",
        3000, FAN_GUIDE),
    "zigbee-presence-sensors": _p("presence-sensors", "Presence sensors", "sensor", "The Best Zigbee Presence Sensors",
        "mmWave presence sensors that know when you're sitting still, ranked.",
        "We pulled the Zigbee mmWave presence sensors on Amazon and scored them on rating, review volume, and features: radar band, light sensing, and open Zigbee 3.0 pairing.",
        1000, PRESENCE_GUIDE),
    "wifi-presence-sensors": _p("presence-sensors", "Presence sensors", "sensor", "The Best Wi-Fi Presence Sensors",
        "Wi-Fi and Bluetooth mmWave presence sensors, including Home Assistant favorites, ranked.",
        "We pulled the Wi-Fi presence sensors on Amazon and scored them on rating, review volume, and features: zones, local Home Assistant support, and extra sensors.",
        2500, PRESENCE_GUIDE),
    "matter-presence-sensors": _p("presence-sensors", "Presence sensors", "sensor", "The Best Matter Presence Sensors",
        "Presence sensors that work with every major smart home platform.",
        "Matter presence sensors are new, so this list is short. We scored the ones on Amazon on rating, review volume, and features.",
        1000, PRESENCE_GUIDE),
    "zigbee-blinds": _p("blinds", "Blinds and shades", "shade", "The Best Zigbee Smart Blinds and Shade Motors",
        "Zigbee shade motors and motorized blinds, ranked.",
        "We pulled the Zigbee blinds and roller shade motors on Amazon and scored them on rating, review volume, and features: retrofit fit, battery life, and remotes.",
        200, BLIND_GUIDE),
    "wifi-blinds": _p("blinds", "Blinds and shades", "shade", "The Best Wi-Fi Smart Blinds and Curtains",
        "Motorized shades, blind kits, and curtain tracks with app and voice control, ranked.",
        "We pulled the Wi-Fi smart blinds and curtain systems on Amazon and scored them on rating, review volume, and features. Several popular shades use a radio remote plus a Wi-Fi hub; the table shows which.",
        1500, BLIND_GUIDE),
    "bluetooth-blinds": _p("blinds", "Blinds and shades", "robot", "The Best Smart Curtain and Blind Robots",
        "SwitchBot curtain openers and blind tilters that retrofit what you already have, ranked.",
        "We pulled the Bluetooth curtain robots and blind tilters on Amazon and scored them on rating, review volume, and features: rod type, solar charging, and Matter through a hub.",
        2000, BLIND_GUIDE),
    "wifi-ir-remotes": _p("ir-remotes", "IR blasters and remotes", "remote", "The 10 Best Smart IR Blasters and Universal Remotes",
        "Wi-Fi IR blasters that bring TVs, ACs, and fans into your smart home, ranked.",
        "We pulled the Wi-Fi IR blasters and universal remote hubs on Amazon and scored them on rating, review volume, and features: RF support, temperature sensors, and Matter.",
        20000, IR_GUIDE),
    "wifi-air-purifiers": _p("air-purifiers", "Air purifiers", "purifier", "The 10 Best Smart Air Purifiers",
        "Wi-Fi air purifiers with app control and air quality sensors, ranked from live Amazon data.",
        "We pulled the best-selling smart air purifiers on Amazon and scored them on rating, review volume, and features: room coverage, a built-in air quality sensor, and smart home support.",
        50000, PURIFIER_GUIDE),
    "matter-air-purifiers": _p("air-purifiers", "Air purifiers", "purifier", "The Best Matter Air Purifiers",
        "Air purifiers that work with Apple Home, Google Home, Alexa, SmartThings, and Home Assistant.",
        "We pulled the air purifiers on Amazon whose listings name Matter or HomeKit support and scored them on rating, review volume, and features.",
        1000, PURIFIER_GUIDE),
    "wifi-ac-controllers": _p("ac-controllers", "AC controllers", "controller", "The Best Smart AC Controllers for Mini-Splits and Window Units",
        "Make a mini-split, window, or portable AC smart, ranked from live Amazon data.",
        "We pulled the smart AC controllers on Amazon and scored them on rating, review volume, and features: temperature sensing, geofencing, and smart home support.",
        5000, AC_GUIDE),
    "wifi-energy-monitors": _p("energy-monitors", "Energy monitors", "monitor", "The Best Home Energy Monitors",
        "Panel-mounted monitors that show what your home and each circuit use, ranked.",
        "We pulled the whole-home energy monitors on Amazon and scored them on rating, review volume, and features: circuit-level sensors, local control, and Home Assistant support.",
        1000, ENERGY_GUIDE),
    "z-wave-outlets": _p("outlets", "In-wall outlets", "outlet", "The Best Z-Wave In-Wall Smart Outlets",
        "Z-Wave receptacles that replace a standard outlet, ranked.",
        "Z-Wave in-wall outlets are a small category. We scored the ones on Amazon on rating, review volume, and features.",
        300, OUTLET_GUIDE),
    "wifi-outlets": _p("outlets", "In-wall outlets", "outlet", "The Best Wi-Fi In-Wall Smart Outlets",
        "Smart receptacles that replace a standard outlet, no plug-in adapter, ranked.",
        "We pulled the Wi-Fi in-wall smart outlets on Amazon and scored them on rating, review volume, and features: individually controlled sockets, USB ports, and tamper resistance.",
        5000, OUTLET_GUIDE),
    "matter-outlets": _p("outlets", "In-wall outlets", "outlet", "The Best Matter In-Wall Smart Outlets",
        "In-wall outlets that work with every major smart home platform.",
        "Matter in-wall outlets are new, so this list is short. We scored the ones on Amazon on rating, review volume, and features.",
        500, OUTLET_GUIDE),
    "wifi-security-systems": _p("security-systems", "Security systems", "system", "The 10 Best DIY Home Security Systems",
        "Alarm kits with sensors, keypads, and sirens you install yourself, ranked from live Amazon data.",
        "We pulled the DIY home security kits on Amazon and scored them on rating, review volume, and features: optional professional monitoring, cellular backup, and smart home support.",
        20000, SECURITY_GUIDE),
    "wifi-mesh-routers": _p("mesh-routers", "Mesh Wi-Fi routers", "system", "The 10 Best Mesh Wi-Fi Systems for Smart Homes",
        "Mesh routers that keep dozens of smart devices online, ranked from live Amazon data.",
        "We pulled the best-selling mesh Wi-Fi systems on Amazon and scored them on rating, review volume, and features: Wi-Fi 6 or 7, coverage, and a built-in smart home hub.",
        30000, MESH_GUIDE),
    "wifi-ev-chargers": _p("ev-chargers", "EV chargers", "charger", "The 10 Best Smart Level 2 EV Chargers",
        "Wi-Fi home EV chargers with scheduling and charging history, ranked.",
        "We pulled the Level 2 home EV chargers on Amazon and scored them on rating, review volume, and features: amperage, safety certification, and Wi-Fi app control.",
        3000, EV_GUIDE),
    "wifi-pet-feeders": _p("pet-feeders", "Pet feeders", "feeder", "The 10 Best Smart Pet Feeders",
        "Wi-Fi automatic feeders for cats and dogs, ranked from live Amazon data.",
        "We pulled the Wi-Fi automatic pet feeders on Amazon and scored them on rating, review volume, and features: cameras, battery backup, and capacity.",
        10000, PET_FEEDER_GUIDE),
    "wifi-pet-cameras": _p("pet-cameras", "Pet cameras", "camera", "The 10 Best Pet Cameras",
        "Treat-tossing and pan-tilt cameras for checking on pets, ranked.",
        "We pulled the pet cameras on Amazon and scored them on rating, review volume, and features: treat tossing, 360-degree view, and whether core features need a subscription.",
        20000, PET_CAM_GUIDE),
    "wifi-baby-monitors": _p("baby-monitors", "Baby monitors", "monitor", "The 10 Best Smart Baby Monitors",
        "Wi-Fi baby monitors with phone apps and parent displays, ranked.",
        "We pulled the smart baby monitors on Amazon and scored them on rating, review volume, and features: a parent display, pan and tilt, and no-subscription use.",
        20000, BABY_GUIDE),
    "wifi-robot-mowers": _p("robot-mowers", "Robot lawn mowers", "mower", "The Best Robot Lawn Mowers",
        "Wire-free and boundary-wire robot mowers with app control, ranked.",
        "We pulled the robot lawn mowers on Amazon and scored them on rating, review volume, and features: wire-free navigation, lawn size, and all-wheel drive.",
        500, MOWER_GUIDE),
}
