"""Page copy for batch 10: outdoor lights, floodlight cameras, outdoor plugs, power strips,
humidifiers, dehumidifiers, space heaters, ceiling fans, Wi-Fi weather stations, bird feeders,
video intercoms, Z-Wave sirens/multisensors/range extenders/garage/valves, Zigbee sirens/
vibration sensors/repeaters/thermostats, Matter blinds/temperature/buttons/garage/irrigation,
Caseta plug-in dimmers and occupancy sensors, RF remote outlets, and Bluetooth padlocks.
Imported at the bottom of meta.py."""
from meta_batch3 import _p, SENSOR_BATT

OUTDOOR_LIGHT_GUIDE = [
    {"q": "Permanent outdoor lights or string lights?",
     "a": "Permanent lights mount under the eaves or along the roofline and stay up all year, with colors you change for each holiday. String lights hang on patios and fences and come down when you want. Permanent kits cost more and take an afternoon to install."},
    {"q": "Are smart outdoor lights weatherproof?",
     "a": "Check the IP rating on the listing. IP65 handles rain and sprinklers; IP67 can survive brief submersion. The power adapter usually needs a covered outdoor outlet."},
    {"q": "Do they need a hub?",
     "a": "Most outdoor light kits connect over Wi-Fi with Bluetooth for setup, so no hub. Philips Hue outdoor lights need the Hue Bridge."},
]
FLOOD_GUIDE = [
    {"q": "Floodlight camera or regular outdoor camera?",
     "a": "A floodlight camera adds bright motion-activated lights, which light up a driveway or backyard and give color night video. It usually replaces an existing outdoor light fixture, so it's hardwired."},
    {"q": "Do floodlight cameras need wiring?",
     "a": "Most mount on a junction box in place of an existing light. Some plug into an outdoor outlet, and a few run on batteries and solar panels, with dimmer lights."},
    {"q": "Do I need a subscription?",
     "a": "It depends on the brand. Ring and Arlo keep recorded video behind a plan; eufy, Reolink, and some others record to local storage for free. Each listing's fee notes are in its pros and cons."},
]
OUTDOOR_PLUG_GUIDE = [
    {"q": "What makes an outdoor smart plug different?",
     "a": "It's weatherproof (look for IP44 or better), usually has two or more outlets, and often a longer cord. Use it for holiday lights, pond pumps, and patio lights."},
    {"q": "Can I leave it out in the rain?",
     "a": "Rated plugs handle rain, but point the outlets down and keep them off the ground. Plug them into a GFCI-protected outdoor outlet with an in-use cover."},
    {"q": "Will it reach my Wi-Fi?",
     "a": "Outdoor outlets are often far from the router. If your phone has a weak signal where the plug goes, the plug will too. A mesh router or extender fixes that."},
]
STRIP_GUIDE = [
    {"q": "Smart power strip or several smart plugs?",
     "a": "A strip puts three to six individually controlled outlets, and usually USB ports, in one place, which suits a desk or entertainment center. Smart plugs suit single lamps spread around the house."},
    {"q": "Does a smart power strip protect against surges?",
     "a": "Only if the listing gives a joule rating. Many smart strips have surge protection, but some don't; check before plugging in a computer or TV."},
    {"q": "Can each outlet be controlled separately?",
     "a": "On most smart strips, yes: each outlet appears as its own switch in the app and in Alexa or Google. USB ports are usually switched together."},
]
HUMID_GUIDE = [
    {"q": "What humidity should my home be?",
     "a": "Aim for 40 to 50 percent. Below 30 percent, skin, sinuses, and wood floors dry out; above 60 percent, mold and dust mites thrive. A smart humidifier holds a target level automatically."},
    {"q": "Warm mist or cool mist?",
     "a": "Cool mist uses less power and is safer around kids. Warm mist feels nicer in winter and boils the water, but uses more electricity. Some models do both."},
    {"q": "What does the smart part add?",
     "a": "Remote control, schedules, a humidity target, refill and filter alerts, and voice control through Alexa or Google."},
]
DEHUMID_GUIDE = [
    {"q": "What size dehumidifier do I need?",
     "a": "Capacity is measured in pints of water removed per day. Around 20-35 pints suits a bedroom or small basement; 50 pints suits a large damp basement. Bigger units also cover more square feet."},
    {"q": "Can it drain on its own?",
     "a": "Most have a hose port for continuous drainage into a floor drain, and some have a built-in pump to push water up into a sink. Otherwise you empty the bucket."},
    {"q": "What does the smart part add?",
     "a": "A full-bucket alert on your phone, a humidity target, schedules, and remote control, which matters most for a basement you don't visit every day."},
]
HEATER_GUIDE = [
    {"q": "Are smart space heaters safe?",
     "a": "Look for tip-over and overheat protection and a UL or ETL listing. Plug a heater straight into a wall outlet, never a power strip or a regular smart plug."},
    {"q": "Why not just use a smart plug?",
     "a": "Most heaters draw close to a plug's limit for hours, and many heater manuals forbid timers and smart plugs. A heater with Wi-Fi built in runs schedules and a thermostat safely."},
    {"q": "How much does a space heater cost to run?",
     "a": "A 1,500 W heater on high uses 1.5 kWh an hour, about 25 cents at the US average rate. Running it on a thermostat setting instead of full blast cuts that a lot."},
]
FAN_GUIDE = [
    {"q": "Smart ceiling fan or a smart fan control?",
     "a": "A smart fan has Wi-Fi in the motor and light, so you get app control, schedules, and voice control without changing your wall switch. A smart wall control makes an existing fan smart without replacing it."},
    {"q": "Do smart ceiling fans need a hub?",
     "a": "Most connect over Wi-Fi to the maker's app and work with Alexa and Google. Some use Bluetooth for setup."},
    {"q": "What size fan do I need?",
     "a": "Roughly 42-48 inches for a bedroom up to 150 square feet, 52 inches for a typical living room, and 60 inches or more for large open rooms."},
]
WEATHER_GUIDE = [
    {"q": "What does a Wi-Fi weather station do that an RF one doesn't?",
     "a": "It uploads readings to the internet, so you can see your backyard conditions from anywhere, get alerts, and share data with services like Weather Underground. Many also work with Home Assistant."},
    {"q": "Where should the outdoor sensor go?",
     "a": "In open air about five feet off the ground, away from walls, roofs, and pavement, which skew temperature. Wind and rain sensors need to be higher and clear of obstructions."},
    {"q": "Does it need a hub?",
     "a": "Most use an indoor display or small gateway that receives the outdoor sensor by radio and connects to Wi-Fi. It's included in the kit."},
]
BIRD_GUIDE = [
    {"q": "How do smart bird feeders identify birds?",
     "a": "A camera takes photos or video when a bird lands, and AI in the app names the species. Some brands charge a subscription for identification or cloud video; check each pick's notes."},
    {"q": "Will squirrels raid it?",
     "a": "Probably. Mount it on a pole with a baffle, away from trees and fences squirrels can jump from."},
    {"q": "How is it powered?",
     "a": "Most run on a rechargeable battery, and many include or offer a solar panel so you rarely need to bring it inside."},
]
INTERCOM_GUIDE = [
    {"q": "What's a video intercom?",
     "a": "An outdoor station with a camera and button, linked to an indoor screen or your phone, so you can see and talk to visitors and often unlock a gate or door."},
    {"q": "Video intercom or video doorbell?",
     "a": "A doorbell is a single camera at one door. An intercom system adds indoor screens in several rooms, and often gate or door release, which suits gated homes and multi-unit buildings."},
    {"q": "Can it open a gate?",
     "a": "Many have a relay output for an electric lock or gate opener. Check the listing for unlock support and the lock voltage it handles."},
]
SIREN_GUIDE = [
    {"q": "Why add a smart siren?",
     "a": "A siren turns your sensors into an alarm: a door opening at night, a leak, or smoke can sound it, without a monitored alarm system. Many also chime softly for doors or announce events."},
    {"q": "How loud is loud enough?",
     "a": "Around 100-110 dB indoors is plenty to wake a house and scare off an intruder. Several models let you pick quieter chimes for everyday alerts."},
    {"q": "Battery or plug-in?",
     "a": "Plug-in sirens also act as mesh repeaters, which strengthens the network. Battery models can go anywhere but don't repeat."},
]
MULTI_GUIDE = [
    {"q": "What does a multisensor measure?",
     "a": "Usually motion plus temperature, humidity, and light, and sometimes vibration or UV. One device covers a room's automations: lights on motion, fans on humidity, blinds on light."},
    {"q": "Battery or USB power?",
     "a": "USB-powered multisensors report more often and act as repeaters. Battery ones go anywhere but check in less often."},
    SENSOR_BATT,
]
EXTENDER_GUIDE = [
    {"q": "Do I need a range extender?",
     "a": "If devices far from your hub drop off or respond slowly, yes. Every plug-in Z-Wave or Zigbee device already repeats, but a dedicated extender is cheap and can sit exactly where the mesh is weak."},
    {"q": "Where should it go?",
     "a": "Halfway between the hub and the devices that drop out, on an outlet that's always powered."},
    {"q": "Does it work with any hub?",
     "a": "Z-Wave extenders work with any Z-Wave controller in your region. Zigbee repeaters work with most Zigbee hubs, but some only repeat for their own brand's devices."},
]
GARAGE_GUIDE = [
    {"q": "Will it work with my garage door opener?",
     "a": "Most controllers wire to the opener's wall-button terminals, which works with almost any opener with a standard push button. Newer openers with encrypted wall buttons may need an adapter; check the listing."},
    {"q": "Is it safe to close the door remotely?",
     "a": "Good controllers flash and beep before closing, as UL 325 requires, and use a tilt sensor to confirm the door's position. Never close a door you can't see without that warning."},
    {"q": "Does it need a hub?",
     "a": "Z-Wave controllers need a Z-Wave hub. Matter controllers work with Apple Home, Google Home, Alexa, SmartThings, and Home Assistant."},
]
VALVE_GUIDE = [
    {"q": "How does a smart water valve work?",
     "a": "A motorized actuator turns your main water valve (or replaces it), so you can shut water off from your phone or automatically when a leak sensor gets wet."},
    {"q": "Do I need a plumber?",
     "a": "Actuators that clamp onto an existing quarter-turn ball valve install without cutting a pipe. In-line valves need a plumber."},
    {"q": "Does it need a hub?",
     "a": "Z-Wave valves need a Z-Wave hub. Pair them with leak sensors on the same hub so a leak closes the valve automatically."},
]
VIBRATION_GUIDE = [
    {"q": "What can a vibration sensor detect?",
     "a": "Knocks, tilts, and drops: a washer or dryer finishing, a mailbox opening, a window being forced, or a door being knocked on."},
    {"q": "Can it tell me when the laundry is done?",
     "a": "Yes. Stick it on the washer or dryer and set an automation for when vibration stops for a few minutes."},
    SENSOR_BATT,
]
THERMO_GUIDE = [
    {"q": "Will a Zigbee thermostat work with my HVAC?",
     "a": "Check the listing's system list: most handle standard gas, electric, and heat pump systems. Many need a C-wire for power."},
    {"q": "Zigbee thermostat or Wi-Fi thermostat?",
     "a": "A Zigbee thermostat runs locally on your hub, which suits Home Assistant and Hubitat users who want control without a cloud account. Wi-Fi thermostats have richer apps."},
    {"q": "Do I need a hub?",
     "a": "Yes, a Zigbee hub such as Home Assistant with a coordinator, Hubitat, SmartThings, or Homey."},
]
MATTER_BLIND_GUIDE = [
    {"q": "Matter blinds: Wi-Fi or Thread?",
     "a": "Most Matter shades use Thread, which runs for months on a battery but needs a Thread border router (a HomePod mini, Apple TV, recent Nest Hub, or some Echo models). Wi-Fi shades need no border router but drain batteries faster."},
    {"q": "Retrofit motor or complete shade?",
     "a": "Complete shades come made to measure. Retrofit motors and tilt kits automate shades or blinds you already own."},
    {"q": "Will they work with my system?",
     "a": "Matter shades work with Apple Home, Google Home, Alexa, SmartThings, and Home Assistant."},
]
MATTER_TEMP_GUIDE = [
    {"q": "Why a Matter temperature sensor?",
     "a": "It reports to Apple Home, Google Home, Alexa, SmartThings, and Home Assistant at once, so you can trigger a fan, heater, or thermostat from any of them."},
    {"q": "Thread or Wi-Fi?",
     "a": "Thread sensors run for a year or more on a coin cell but need a Thread border router. Wi-Fi sensors use more power."},
    SENSOR_BATT,
]
MATTER_BUTTON_GUIDE = [
    {"q": "What can a smart button do?",
     "a": "Run any scene or automation with a press, double press, or long press: turn off every light, start a bedtime routine, or open the garage."},
    {"q": "Do Matter buttons need a hub?",
     "a": "Most use Thread, which needs a Thread border router, plus a Matter controller such as Apple Home, Google Home, or Home Assistant."},
    SENSOR_BATT,
]
IRRIGATION_GUIDE = [
    {"q": "Sprinkler controller or hose timer?",
     "a": "A controller replaces the box that runs an in-ground sprinkler system. A hose timer screws onto an outdoor spigot and waters through a hose."},
    {"q": "Does weather skipping save water?",
     "a": "Yes. Timers that skip watering when rain is forecast or the soil is wet can cut outdoor water use noticeably."},
    {"q": "Do Matter timers need a hub?",
     "a": "Thread models need a Thread border router; all of them need a Matter controller such as Apple Home or Google Home."},
]
CASETA_PLUG_GUIDE = [
    {"q": "What's a Caseta plug-in dimmer?",
     "a": "A module that plugs into a wall outlet and dims a lamp plugged into it, controlled from the Lutron app, a Pico remote, or Alexa, Google, and Apple Home through the Lutron bridge."},
    {"q": "Does it need the Lutron bridge?",
     "a": "For app and voice control, yes. Without the bridge you can still pair it straight to a Pico remote."},
    {"q": "What bulbs work?",
     "a": "Dimmable LED and incandescent bulbs. Check the wattage limit on the listing."},
]
CASETA_SENSOR_GUIDE = [
    {"q": "Occupancy or vacancy?",
     "a": "Occupancy mode turns lights on when you walk in and off when you leave. Vacancy mode only turns them off, so you switch them on yourself, which suits bedrooms."},
    {"q": "Does it work without the bridge?",
     "a": "It pairs straight to Caseta dimmers and switches without a bridge. With the bridge you can use it in the Lutron app and other automations."},
    SENSOR_BATT,
]
RF_OUTLET_GUIDE = [
    {"q": "What's an RF remote outlet?",
     "a": "A plug-in outlet switched by a small handheld radio remote, with no Wi-Fi, app, or hub. It's the simplest way to switch lamps, holiday lights, and hard-to-reach outlets."},
    {"q": "How far does the remote reach?",
     "a": "Usually 80-100 feet, and through walls, because 433 MHz radio passes through them better than Wi-Fi."},
    {"q": "Can I make them work with Alexa or Home Assistant?",
     "a": "Not directly. An RF bridge, such as the ones on our RF bridges page, can learn the remote's codes and add them to a smart home system."},
]
PADLOCK_GUIDE = [
    {"q": "How does a Bluetooth padlock open?",
     "a": "With your phone over Bluetooth, a fingerprint on some models, or a backup code or key. You can share access with others through the app."},
    {"q": "Is it as strong as a regular padlock?",
     "a": "The shackle and body matter more than the electronics. Look for a hardened steel shackle and a weather rating for outdoor use."},
    {"q": "What if the battery dies?",
     "a": "Most warn you well before and charge over USB. Many also have a key or jump-start contacts as a backup."},
]

PAGES = {
    "wifi-outdoor-lights": _p("outdoor-lights", "Outdoor lights", "light", "The 10 Best Smart Outdoor Lights",
        "Permanent roofline lights and smart string lights you control from your phone, ranked from live Amazon data.",
        "We pulled the best-selling smart outdoor lights on Amazon, from permanent eave lights to patio string lights, and scored them on rating, review volume, and features: weatherproofing, multicolor effects, and voice control.",
        20000, OUTDOOR_LIGHT_GUIDE),
    "wifi-floodlight-cameras": _p("floodlight-cameras", "Floodlight cameras", "camera", "The 10 Best Floodlight Cameras",
        "Wi-Fi security cameras with built-in floodlights for driveways and backyards, ranked.",
        "We pulled the floodlight cameras on Amazon and scored them on rating, review volume, and features: video resolution, light brightness, local storage, and whether recordings need a subscription.",
        20000, FLOOD_GUIDE),
    "wifi-outdoor-plugs": _p("outdoor-plugs", "Outdoor smart plugs", "plug", "The 10 Best Outdoor Smart Plugs",
        "Weatherproof Wi-Fi plugs for holiday lights, pumps, and patio lights, ranked.",
        "We pulled the outdoor smart plugs on Amazon and scored them on rating, review volume, and features: weather rating, number of outlets, independent control, and range.",
        20000, OUTDOOR_PLUG_GUIDE),
    "matter-outdoor-plugs": _p("outdoor-plugs", "Outdoor smart plugs", "plug", "The Best Matter Outdoor Smart Plugs",
        "Weatherproof plugs that work with Apple Home, Google Home, Alexa, SmartThings, and Home Assistant.",
        "We pulled the outdoor smart plugs on Amazon whose listings name Matter support and scored them on rating, review volume, and features.",
        5000, OUTDOOR_PLUG_GUIDE),
    "wifi-power-strips": _p("power-strips", "Smart power strips", "strip", "The 10 Best Smart Power Strips",
        "Wi-Fi power strips with individually controlled outlets, ranked.",
        "We pulled the smart power strips on Amazon and scored them on rating, review volume, and features: outlet count, independent control, USB ports, surge protection, and energy monitoring.",
        20000, STRIP_GUIDE),
    "wifi-humidifiers": _p("humidifiers", "Humidifiers", "humidifier", "The 10 Best Smart Humidifiers",
        "Wi-Fi humidifiers that hold a humidity target and alert you when they need water, ranked.",
        "We pulled the smart humidifiers on Amazon and scored them on rating, review volume, and features: tank size, auto humidity mode, warm mist, and voice control.",
        20000, HUMID_GUIDE),
    "wifi-dehumidifiers": _p("dehumidifiers", "Dehumidifiers", "dehumidifier", "The Best Smart Dehumidifiers",
        "Wi-Fi dehumidifiers for basements and damp rooms, ranked.",
        "We pulled the dehumidifiers on Amazon with Wi-Fi app control and scored them on rating, review volume, and features: capacity, continuous drainage, a built-in pump, and full-bucket alerts.",
        10000, DEHUMID_GUIDE),
    "wifi-space-heaters": _p("space-heaters", "Space heaters", "heater", "The Best Smart Space Heaters",
        "Wi-Fi space heaters with thermostats, schedules, and safety cutoffs, ranked.",
        "We pulled the space heaters on Amazon with Wi-Fi app control and scored them on rating, review volume, and features: thermostat control, tip-over protection, and voice control.",
        10000, HEATER_GUIDE),
    "wifi-ceiling-fans": _p("ceiling-fans", "Ceiling fans", "fan", "The 10 Best Smart Ceiling Fans",
        "Ceiling fans with Wi-Fi built in, so you control the fan and light from your phone or voice, ranked.",
        "We pulled the smart ceiling fans on Amazon and scored them on rating, review volume, and features: a dimmable light, DC motor, reverse mode, and voice control.",
        10000, FAN_GUIDE),
    "wifi-weather-stations": _p("weather-stations", "Weather stations", "station", "The Best Wi-Fi Weather Stations",
        "Backyard weather stations that upload to the internet and your phone, ranked.",
        "We pulled the Wi-Fi weather stations on Amazon and scored them on rating, review volume, and features: wind and rain sensors, an indoor display, and Weather Underground or Home Assistant support.",
        5000, WEATHER_GUIDE),
    "wifi-bird-feeders": _p("bird-feeders", "Bird feeders", "feeder", "The 10 Best Smart Bird Feeders",
        "Camera bird feeders that photograph and identify your visitors, ranked.",
        "We pulled the smart bird feeders on Amazon and scored them on rating, review volume, and features: video resolution, AI bird identification, solar power, and whether identification needs a subscription.",
        10000, BIRD_GUIDE),
    "wifi-video-intercoms": _p("intercoms", "Video intercoms", "intercom", "The Best Video Intercoms",
        "Wi-Fi video intercom systems for gates, front doors, and multi-unit homes, ranked.",
        "We pulled the video intercom systems on Amazon and scored them on rating, review volume, and features: indoor screens, phone app access, and gate or door release.",
        3000, INTERCOM_GUIDE),
    "z-wave-sirens": _p("sirens", "Sirens", "siren", "The Best Z-Wave Sirens",
        "Z-Wave sirens and chimes for DIY alarms and alerts, ranked.",
        "We pulled the Z-Wave sirens on Amazon and scored them on rating, review volume, and features: volume, selectable tones, and plug-in power that repeats the mesh.",
        1000, SIREN_GUIDE),
    "z-wave-multisensors": _p("multisensors", "Multisensors", "sensor", "The Best Z-Wave Multisensors",
        "Z-Wave sensors that combine motion, temperature, humidity, and light, ranked.",
        "We pulled the Z-Wave multisensors on Amazon and scored them on rating, review volume, and features: how many readings they take, USB power, and 800 Series chips.",
        1000, MULTI_GUIDE),
    "z-wave-range-extenders": _p("range-extenders", "Range extenders", "extender", "The Best Z-Wave Range Extenders",
        "Z-Wave repeaters that strengthen a weak mesh, ranked.",
        "We pulled the Z-Wave range extenders on Amazon and scored them on rating, review volume, and features: 800 Series and Long Range support, and a pass-through outlet.",
        1000, EXTENDER_GUIDE),
    "z-wave-garage-openers": _p("garage-openers", "Garage door openers", "opener", "The Best Z-Wave Garage Door Controllers",
        "Z-Wave controllers that make an existing garage door opener smart, ranked.",
        "We pulled the Z-Wave garage door controllers on Amazon and scored them on rating, review volume, and features: a tilt sensor, warning lights and sound, and opener compatibility.",
        1000, GARAGE_GUIDE),
    "z-wave-water-valves": _p("water-valves", "Water shutoff valves", "valve", "The Best Z-Wave Water Shutoff Valves",
        "Z-Wave valve actuators that shut off your water from your phone or when a leak is found, ranked.",
        "We pulled the Z-Wave water shutoff valves on Amazon and scored them on rating, review volume, and features: install without a plumber, pipe sizes, and leak sensors in the box.",
        1000, VALVE_GUIDE),
    "zigbee-sirens": _p("sirens", "Sirens", "siren", "The Best Zigbee Sirens",
        "Zigbee sirens and chimes for DIY alarms and alerts, ranked.",
        "We pulled the Zigbee sirens on Amazon and scored them on rating, review volume, and features: volume, built-in light, and plug-in power.",
        1000, SIREN_GUIDE),
    "zigbee-vibration-sensors": _p("vibration-sensors", "Vibration sensors", "sensor", "The Best Zigbee Vibration Sensors",
        "Zigbee sensors that detect knocks, tilts, and appliances finishing, ranked.",
        "We pulled the Zigbee vibration sensors on Amazon and scored them on rating, review volume, and features: tilt and drop detection, adjustable sensitivity, and battery life.",
        1000, VIBRATION_GUIDE),
    "zigbee-repeaters": _p("range-extenders", "Range extenders", "repeater", "The Best Zigbee Repeaters",
        "Zigbee repeaters that strengthen a weak mesh, ranked.",
        "We pulled the Zigbee repeaters and range extenders on Amazon and scored them on rating, review volume, and features: Zigbee 3.0 support, hub compatibility, and size.",
        1000, EXTENDER_GUIDE),
    "zigbee-thermostats": _p("thermostats", "Thermostats", "thermostat", "The Best Zigbee Thermostats",
        "Thermostats that run locally on a Zigbee hub, ranked.",
        "We pulled the Zigbee thermostats on Amazon and scored them on rating, review volume, and features: heat pump support, a C-wire requirement, and hub compatibility.",
        1000, THERMO_GUIDE),
    "matter-blinds": _p("blinds", "Blinds and shades", "shade", "The Best Matter Blinds and Shades",
        "Matter shades and blind motors for Apple Home, Google Home, Alexa, SmartThings, and Home Assistant, ranked.",
        "We pulled the smart blinds, shades, and motors on Amazon whose listings name Matter support and scored them on rating, review volume, and features.",
        2000, MATTER_BLIND_GUIDE),
    "matter-temperature-sensors": _p("temperature-sensors", "Temperature sensors", "sensor", "The Best Matter Temperature Sensors",
        "Temperature and humidity sensors that work across every major smart home system, ranked.",
        "We pulled the temperature and humidity sensors on Amazon whose listings name Matter support and scored them on rating, review volume, and features: display, accuracy, and battery life.",
        2000, MATTER_TEMP_GUIDE),
    "matter-buttons": _p("buttons", "Buttons and remotes", "button", "The Best Matter Buttons and Remotes",
        "Smart buttons and remotes that run scenes in Apple Home, Google Home, and Home Assistant, ranked.",
        "We pulled the smart buttons and remotes on Amazon whose listings name Matter support and scored them on rating, review volume, and features.",
        2000, MATTER_BUTTON_GUIDE),
    "matter-garage-openers": _p("garage-openers", "Garage door openers", "opener", "The Best Matter Garage Door Openers",
        "Garage door controllers that work with Apple Home, Google Home, Alexa, SmartThings, and Home Assistant, ranked.",
        "We pulled the smart garage door controllers on Amazon whose listings name Matter support and scored them on rating, review volume, and features.",
        5000, GARAGE_GUIDE),
    "matter-irrigation": _p("sprinklers", "Sprinklers and timers", "timer", "The Best Matter Sprinkler and Hose Timers",
        "Watering timers and sprinkler controllers that work across smart home systems, ranked.",
        "We pulled the sprinkler controllers and hose timers on Amazon whose listings name Matter support and scored them on rating, review volume, and features.",
        2000, IRRIGATION_GUIDE),
    "lutron-plug-in-dimmers": _p("dimmers", "Dimmers", "dimmer", "The Best Lutron Caseta Plug-in Dimmers",
        "Caseta plug-in lamp dimmers and switches, ranked.",
        "We pulled Lutron's Caseta plug-in lamp dimmers and switches on Amazon and scored them on rating, review volume, and features.",
        5000, CASETA_PLUG_GUIDE),
    "lutron-occupancy-sensors": _p("motion-sensors", "Motion sensors", "sensor", "The Best Lutron Caseta Occupancy Sensors",
        "Caseta motion sensors that turn your Lutron lights on and off, ranked.",
        "We pulled Lutron's Caseta occupancy and vacancy sensors on Amazon and scored them on rating, review volume, and features.",
        3000, CASETA_SENSOR_GUIDE),
    "rf-remote-outlets": _p("smart-plugs", "Smart plugs", "outlet", "The 10 Best Remote Control Outlets",
        "433 MHz plug-in outlets with handheld remotes: no Wi-Fi, app, or hub, ranked.",
        "We pulled the remote control outlet kits on Amazon and scored them on rating, review volume, and features: how many outlets and remotes come in the kit, range, and outdoor use.",
        20000, RF_OUTLET_GUIDE),
    "bluetooth-padlocks": _p("padlocks", "Padlocks", "padlock", "The Best Bluetooth Smart Padlocks",
        "Padlocks you open with your phone or a fingerprint, ranked.",
        "We pulled the Bluetooth smart padlocks on Amazon and scored them on rating, review volume, and features: fingerprint unlock, weatherproofing, backup access, and battery life.",
        10000, PADLOCK_GUIDE),
}
