"""Page copy for batch 12: desk lamps, flush mount lights, power stations, water monitors, sunrise
alarms, pool cleaners, smart scales, curtain openers, path lights, portable ACs, propane monitors,
mailbox sensors, Thread sensors / bulbs / locks, Matter lamps / cameras / air quality monitors,
Zigbee air quality sensors and curtain motors, Z-Wave keypads. Imported at the bottom of meta.py."""
from meta_batch3 import _p, DOOR_GUIDE, MOTION_GUIDE, LOCK_GUIDE
from meta_batch4 import BULB_GUIDE, CAM_GUIDE
from meta_batch6 import TEMP_GUIDE
from meta_batch8 import AIR_GUIDE
from meta_batch10 import OUTDOOR_LIGHT_GUIDE
from meta_batch11 import LAMP_GUIDE, CEILING_GUIDE

THREAD_Q = {"q": "What do Thread devices need?",
            "a": "A Thread border router, which is built into recent Apple TVs and HomePods, Nest Hubs, some Echo models, and SmartThings and Aqara hubs. With Matter, the device then shows up in Apple Home, Google Home, Alexa, SmartThings, or Home Assistant."}
MATTER_Q = {"q": "Does Matter over Wi-Fi need a hub?",
            "a": "Not a separate one, but you need a Matter controller such as an Apple TV, HomePod, Nest Hub, Echo, or SmartThings hub to add it to your system."}

POWER_GUIDE = [
    {"q": "What size power station do I need?",
     "a": "Add up what you want to run. A fridge needs roughly 1 to 2 kWh a day, a CPAP about 0.5 kWh a night, and a router and phone chargers well under that. Output in watts limits what can run at once; capacity in watt-hours limits how long."},
    {"q": "What does the app add?",
     "a": "Live input and output, remaining runtime, charge limits, and scheduled charging during cheap off-peak hours. Some models also report to Home Assistant."},
    {"q": "Can it back up my whole house?",
     "a": "Only larger systems with a transfer switch or smart panel, sold separately. Most portable units power devices plugged into them, and some offer a UPS-style switchover in a few milliseconds."},
]
WATER_MON_GUIDE = [
    {"q": "Flow monitor or shutoff valve?",
     "a": "A flow monitor watches your water use and spots leaks, dripping toilets, and running hoses. A shutoff valve can also close the main line. Some devices do both; others only alert you."},
    {"q": "Does it need a plumber?",
     "a": "Strap-on meter readers clip around your water meter with no plumbing. Inline monitors and valves are cut into the main line and usually need a plumber."},
    {"q": "Will it catch small leaks?",
     "a": "Most run a nightly check for tiny steady flows, which catches running toilets and drips that a leak puck under the sink won't."},
]
SUNRISE_GUIDE = [
    {"q": "Do sunrise alarms actually help?",
     "a": "Many people wake up more easily to light that brightens over 20 to 30 minutes before the alarm, especially in dark winter months. It's a gentler start, not a cure for poor sleep."},
    {"q": "What does the app add?",
     "a": "Schedules for weekdays and weekends, custom sounds and colors, and wind-down routines without touching the clock. Some lock premium sounds and content behind a subscription."},
    {"q": "Are they good for kids?",
     "a": "Yes. Many double as a sound machine and a stay-in-bed light that turns green when it's OK to get up."},
]
POOL_GUIDE = [
    {"q": "Cordless or corded pool robot?",
     "a": "Cordless robots skip the tangled cable and are easier to drop in, but run 1.5 to 3 hours per charge. Corded models run as long as you want and are usually cheaper for the same cleaning."},
    {"q": "Will it climb walls?",
     "a": "Check the listing. Floor-only models are cheaper; wall and waterline cleaning needs stronger motors and better navigation."},
    {"q": "What does the app add?",
     "a": "Cleaning modes and schedules, battery level, and on some models a map of where it cleaned. Most apps connect over Bluetooth or Wi-Fi when the robot is out of the water."},
]
SCALE_GUIDE = [
    {"q": "How accurate are body composition scales?",
     "a": "Weight is accurate to a few tenths of a pound. Body fat and muscle numbers from foot sensors are estimates; use them to see trends, not exact values."},
    {"q": "Wi-Fi or Bluetooth?",
     "a": "Wi-Fi scales sync on their own every time you step on. Bluetooth scales need your phone nearby with the app open."},
    {"q": "Does it work with Apple Health and Google Fit?",
     "a": "Most do, along with apps like Fitbit or MyFitnessPal. Check the listing for the ones you use."},
]
CURTAIN_GUIDE = [
    {"q": "Curtain robot or curtain motor?",
     "a": "Curtain robots clip onto your existing rod or track and push the curtain along, no tools needed. Motorized tracks replace the rod and are quieter and stronger, but take more work to install."},
    {"q": "Will it work with my rod?",
     "a": "Check the rod type and diameter. Most robots list compatible U-rails, I-rails, and round rods by size."},
    {"q": "Do they need a hub?",
     "a": "Bluetooth robots need the maker's hub for voice control and away-from-home control. Wi-Fi motors connect straight to your router; Zigbee motors need a Zigbee hub."},
]
PORTABLE_AC_GUIDE = [
    {"q": "Portable or window AC?",
     "a": "Window units cool better for the money. Portable units suit windows that can't take a window unit, like casement or sliding windows, or rentals that don't allow them."},
    {"q": "Single hose or dual hose?",
     "a": "Dual-hose units pull outside air to cool the condenser, so they don't create negative pressure that draws warm air in through gaps. They cool large rooms faster."},
    {"q": "What does Wi-Fi add?",
     "a": "Cool the room before you get home, schedules, and Alexa or Google voice control."},
]
PROPANE_GUIDE = [
    {"q": "How do propane tank monitors work?",
     "a": "Most stick to the bottom of the tank and measure the liquid level with ultrasound; others replace the gauge on large tanks. The app shows the level and alerts you before you run out."},
    {"q": "Bluetooth or Wi-Fi?",
     "a": "Bluetooth sensors only update when your phone is nearby. Wi-Fi models or a Wi-Fi bridge send alerts from anywhere."},
    {"q": "Will it fit my tank?",
     "a": "Check the tank sizes listed. Grill tanks (20 lb) and large home tanks usually need different models."},
]
MAILBOX_GUIDE = [
    {"q": "How do mailbox sensors work?",
     "a": "A small sensor inside the mailbox detects the door opening or motion and sends an alert to your phone. Metal mailboxes block radio signals, so most use long-range radio with an indoor hub or receiver."},
    {"q": "Will it reach my house?",
     "a": "Check the stated range. Long-range models reach a quarter mile or more; Wi-Fi models need Wi-Fi coverage at the curb."},
    {"q": "Do they need a hub?",
     "a": "Most do. The hub plugs in indoors and passes alerts to the app."},
]
MATTER_CAM_GUIDE = [
    {"q": "What does Matter add to a camera?",
     "a": "Matter added camera support in 2025, so a Matter camera can stream live video into Apple Home, Google Home, and other Matter apps without the maker's app. Support varies by system, so check what yours shows today."},
] + CAM_GUIDE
KEYPAD_GUIDE = [
    {"q": "What does a Z-Wave keypad do?",
     "a": "It arms and disarms your security system with a code, so guests and kids don't need the app. Your hub's security software, such as Home Assistant's Alarmo or Hubitat Safety Monitor, decides what happens."},
    {"q": "Does it work with any Z-Wave hub?",
     "a": "The keypad itself pairs with any Z-Wave hub, but mapping its buttons and codes to an alarm takes setup. Ring keypads are popular with Home Assistant because of their built-in siren and status lights."},
    {"q": "Battery or wired?",
     "a": "Most run on batteries for months, and some also take USB power for always-on status lights."},
]

PAGES = {
    "wifi-desk-lamps": _p("lamps", "Lamps", "lamp", "The Best Smart Desk and Table Lamps",
        "Wi-Fi desk and table lamps with app and voice control, ranked.",
        "We pulled the smart desk and table lamps on Amazon and scored them on rating, review volume, and features: tunable white, color, brightness, and voice control.",
        10000, LAMP_GUIDE),
    "wifi-flush-mount-lights": _p("ceiling-lights", "Ceiling lights", "light", "The Best Smart Flush Mount Ceiling Lights",
        "Wi-Fi flush mount ceiling lights with tunable white and color, ranked.",
        "We pulled the smart flush mount ceiling lights on Amazon and scored them on rating, review volume, and features: brightness, color and tunable white, and voice control.",
        5000, CEILING_GUIDE),
    "wifi-power-stations": _p("power-stations", "Power stations", "power station", "The Best Smart Portable Power Stations",
        "Battery power stations with app control for outages, camping, and backup, ranked.",
        "We pulled the portable power stations on Amazon with Wi-Fi app control and scored them on rating, review volume, and features: capacity, output, fast charging, and UPS switchover.",
        5000, POWER_GUIDE),
    "wifi-water-monitors": _p("water-monitors", "Water monitors", "monitor", "The Best Smart Water Monitors",
        "Whole-home water flow monitors that catch leaks and track usage, ranked.",
        "We pulled the smart water monitors on Amazon and scored them on rating, review volume, and features: leak detection, automatic shutoff, and plumbing-free installation.",
        2000, WATER_MON_GUIDE),
    "wifi-sunrise-alarms": _p("sunrise-alarms", "Sunrise alarms", "alarm clock", "The Best Smart Sunrise Alarm Clocks",
        "Sunrise alarm clocks with app control and sleep sounds, ranked.",
        "We pulled the sunrise alarm clocks on Amazon with app control and scored them on rating, review volume, and features: sunrise light, sound machine, and app schedules.",
        10000, SUNRISE_GUIDE),
    "wifi-pool-cleaners": _p("pool-cleaners", "Pool cleaners", "pool robot", "The Best Smart Robotic Pool Cleaners",
        "Robotic pool cleaners with app control, ranked.",
        "We pulled the robotic pool cleaners on Amazon with app control and scored them on rating, review volume, and features: cordless operation, wall and waterline cleaning, and runtime.",
        5000, POOL_GUIDE),
    "wifi-smart-scales": _p("scales", "Smart scales", "scale", "The Best Wi-Fi Smart Scales",
        "Wi-Fi bathroom scales that sync your weight automatically, ranked.",
        "We pulled the Wi-Fi smart scales on Amazon and scored them on rating, review volume, and features: automatic Wi-Fi sync, body composition, multiple users, and health app support.",
        20000, SCALE_GUIDE),
    "wifi-curtain-openers": _p("curtain-motors", "Curtain motors", "curtain opener", "The Best Smart Curtain Openers",
        "Curtain robots and motors you can control from your phone or voice, ranked.",
        "We pulled the smart curtain openers on Amazon and scored them on rating, review volume, and features: easy installation, voice control, and light-sensor or schedule automation.",
        5000, CURTAIN_GUIDE),
    "wifi-path-lights": _p("outdoor-lights", "Outdoor lights", "light", "The Best Smart Path and Landscape Lights",
        "Wi-Fi pathway and landscape lights with color and schedules, ranked.",
        "We pulled the smart path and landscape lights on Amazon and scored them on rating, review volume, and features: color and warm white, weather rating, and voice control.",
        5000, OUTDOOR_LIGHT_GUIDE),
    "wifi-portable-air-conditioners": _p("air-conditioners", "Air conditioners", "air conditioner", "The Best Smart Portable Air Conditioners",
        "Portable air conditioners with Wi-Fi app and voice control, ranked.",
        "We pulled the portable air conditioners on Amazon with Wi-Fi control and scored them on rating, review volume, and features: dual-hose or inverter designs, heat mode, and voice control.",
        5000, PORTABLE_AC_GUIDE),
    "bluetooth-propane-monitors": _p("tank-monitors", "Tank monitors", "monitor", "The Best Bluetooth Propane Tank Monitors",
        "Propane tank level sensors that show the level on your phone, ranked.",
        "We pulled the Bluetooth propane tank monitors on Amazon and scored them on rating, review volume, and features: range, Wi-Fi bridge support, tank compatibility, and battery life.",
        2000, PROPANE_GUIDE),
    "wifi-mailbox-sensors": _p("mailbox-sensors", "Mailbox sensors", "sensor", "The Best Smart Mailbox Sensors",
        "Sensors that alert your phone when the mail arrives, ranked.",
        "We pulled the mailbox sensors on Amazon with app alerts and scored them on rating, review volume, and features: range, battery life, and smart home support.",
        1000, MAILBOX_GUIDE),
    "thread-door-sensors": _p("door-sensors", "Door and window sensors", "sensor", "The Best Thread Door and Window Sensors",
        "Thread contact sensors that work through Matter with every major smart home system, ranked.",
        "We pulled the door and window sensors on Amazon whose listings name Thread and scored them on rating, review volume, and features.",
        2000, [THREAD_Q] + DOOR_GUIDE),
    "thread-motion-sensors": _p("motion-sensors", "Motion sensors", "sensor", "The Best Thread Motion Sensors",
        "Thread motion sensors that work through Matter with every major smart home system, ranked.",
        "We pulled the motion sensors on Amazon whose listings name Thread and scored them on rating, review volume, and features.",
        2000, [THREAD_Q] + MOTION_GUIDE),
    "thread-temperature-sensors": _p("temperature-sensors", "Temperature sensors", "sensor", "The Best Thread Temperature Sensors",
        "Thread temperature and humidity sensors for Apple Home, Google Home, Alexa, and more, ranked.",
        "We pulled the temperature and humidity sensors on Amazon whose listings name Thread and scored them on rating, review volume, and features.",
        2000, [THREAD_Q] + TEMP_GUIDE),
    "thread-bulbs": _p("bulbs", "Smart bulbs", "bulb", "The Best Thread Smart Bulbs",
        "Smart bulbs that run on Thread and work with every Matter system, ranked.",
        "We pulled the smart bulbs on Amazon whose listings name Thread and scored them on rating, review volume, and features.",
        5000, [THREAD_Q] + BULB_GUIDE),
    "thread-locks": _p("locks", "Smart locks", "lock", "The Best Thread Smart Locks",
        "Smart locks that run on Thread for fast, low-power control through Matter, ranked.",
        "We pulled the smart locks on Amazon whose listings name Thread and scored them on rating, review volume, and features.",
        2000, [THREAD_Q] + LOCK_GUIDE),
    "matter-lamps": _p("lamps", "Lamps", "lamp", "The Best Matter Smart Lamps",
        "Floor and table lamps that work with Apple Home, Google Home, Alexa, and SmartThings, ranked.",
        "We pulled the smart lamps on Amazon whose listings name Matter support and scored them on rating, review volume, and features.",
        2000, [MATTER_Q] + LAMP_GUIDE),
    "matter-cameras": _p("indoor-cameras", "Indoor cameras", "camera", "The Best Matter Security Cameras",
        "Security cameras whose listings name Matter support, ranked.",
        "We pulled the security cameras on Amazon whose listings name Matter support and scored them on rating, review volume, and features.",
        2000, MATTER_CAM_GUIDE),
    "matter-air-quality-monitors": _p("air-quality-monitors", "Air quality monitors", "monitor", "The Best Matter Air Quality Monitors",
        "Air quality monitors that report to Apple Home, Google Home, and other Matter systems, ranked.",
        "We pulled the air quality monitors on Amazon whose listings name Matter support and scored them on rating, review volume, and features.",
        2000, [MATTER_Q] + AIR_GUIDE),
    "zigbee-air-quality-sensors": _p("air-quality-monitors", "Air quality monitors", "sensor", "The Best Zigbee Air Quality Sensors",
        "Zigbee CO2, VOC, and particle sensors for your smart home hub, ranked.",
        "We pulled the Zigbee air quality sensors on Amazon and scored them on rating, review volume, and features.",
        1000, AIR_GUIDE),
    "zigbee-curtain-motors": _p("curtain-motors", "Curtain motors", "curtain motor", "The Best Zigbee Curtain Motors",
        "Zigbee curtain robots and motorized tracks, ranked.",
        "We pulled the Zigbee curtain motors on Amazon and scored them on rating, review volume, and features.",
        1000, CURTAIN_GUIDE),
    "z-wave-keypads": _p("keypads", "Keypads", "keypad", "The Best Z-Wave Keypads",
        "Z-Wave keypads for arming and disarming your hub's security system, ranked.",
        "We pulled the Z-Wave keypads on Amazon and scored them on rating, review volume, and features.",
        1000, KEYPAD_GUIDE),
}
